services:
  backend:
    build: ./Desafio-backend
    ports:
      - "3000:3000"
    volumes:
      - ./Desafio-backend:/app
      - /app/node_modules
    working_dir: /app
    command: sh start.sh
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: meu_banco
      JWT_PASS: default_secret
      PORT: 3000
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meu_banco
    restart: always
